[package]
name = "common"
version = "0.1.0"
authors = ["leowei"]
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
secp256k1 = { version = "0.28.0", features =["rand" ]}
hex = "0.4"
rand = "0.8"
sha3 = "0.10.8"